-- Al Shaqab Horse Show 2026 - database setup. Paste into Supabase: SQL Editor -> New query -> Run.
-- STEP 1: put YOUR admin e-mail on the line marked  <<<  (the account you will sign in with on admin.html).

create table if not exists public.admins (email text primary key);
insert into public.admins (email) values ('YOUR_ADMIN_EMAIL@example.com') on conflict do nothing;   -- <<<
alter table public.admins enable row level security;   -- no policies: not readable through the API

create or replace function public.is_admin() returns boolean
language sql security definer set search_path = public stable as $$
  select exists (select 1 from public.admins where lower(email) = lower(coalesce(auth.jwt() ->> 'email', '')));
$$;

create table if not exists public.horses (
  id          uuid primary key default gen_random_uuid(),
  pos         bigint generated always as identity,
  class_no    int,
  class_name  text,
  horse_name  text,
  country     text,
  sex         text,
  birth_date  text,
  color       text,
  sire        text,
  dam         text,
  owner       text,
  paid        boolean not null default false,
  updated_at  timestamptz not null default now()
);
create table if not exists public.owner_contacts (
  owner text primary key, email text, phone text, updated_at timestamptz not null default now()
);
create table if not exists public.app_meta (key text primary key, value text);

alter table public.horses         enable row level security;
alter table public.owner_contacts enable row level security;
alter table public.app_meta       enable row level security;

-- everyone (the shared dashboard) can READ horses + last-updated; only the admin can change anything
create policy "read horses"       on public.horses   for select to anon, authenticated using (true);
create policy "admin write horses" on public.horses   for all    to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "read meta"         on public.app_meta for select to anon, authenticated using (true);
create policy "admin write meta"  on public.app_meta for all    to authenticated using (public.is_admin()) with check (public.is_admin());
-- owner e-mail / phone: admin only (never visible on the shared dashboard)
create policy "admin contacts"    on public.owner_contacts for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- live updates for the shared dashboard
alter publication supabase_realtime add table public.horses;

-- STEP 2 (automatic): your 201 catalogue entries
insert into public.horses (class_no, class_name, horse_name, country, sex, birth_date, color, sire, dam, owner, paid) values
  (3,'Yearling Fillies','Roudah Al Jazeel','QA','F','2025-01-14','Bay','Rhan Al Shahania','Carlotta Cj','Al Jazeel Stud',false),
  (3,'Yearling Fillies','Nayyla Al Jazeel','QA','F','2025-03-03','Bay','Exagon Os','D Nashabeyyah','Al Jazeel Stud',false),
  (3,'Yearling Fillies','Nina Al Nasser','QA','F','2025-02-09','Grey','Tm Itaipu','Hattan Al Nasser','Al Nasser Stud - Sheikh Nawaf Bin Nasser Al Thani',false),
  (3,'Yearling Fillies','Ghadnana Al Sraiya','QA','F','2025-01-12','Grey','Wadee Al Shaqab','Alkaydah Al Sraiya','Al Sraiya Stud',false),
  (3,'Yearling Fillies','Bessan Al Sraiya','QA','F','2025-03-20','Grey','Excalibur Ea','Shalfa Al Sraiya','Al Sraiya Stud',false),
  (3,'Yearling Fillies','Hala Al Wajba','QA','F','2025-02-05','Bay','Lr Anselmo','Ss Helen','Al Atheel Stud',false),
  (3,'Yearling Fillies','Ghalya Al Thamer','QA','F','2025-03-15','Bay','D Hayel','Anhar Al Shaqab','Al Atheel Stud',false),
  (3,'Yearling Fillies','Jaflah Al Ammar','QA','F','2025-03-25','Black','Copperfield Ora','Summar Al Ammar','Al Ammar Stud',false),
  (3,'Yearling Fillies','Rayana Al Ammar','QA','F','2025-04-21','Bay','Wf Gawin','Asrar Al Ammar','Al Ammar Stud',false),
  (3,'Yearling Fillies','Shomookh Umm Aludham','QA','F','2025-03-16','Grey','Harbi Al Adwan','Najla Umm Aludham','Mr. Nasser Mohammed M A Al Hajri',false),
  (3,'Yearling Fillies','Somood Umm Aludham','QA','F','2025-01-17','Grey','Tm Itaipu','Najla Umm Aludham','Mr. Mesfer Mohammed Mesfer Al Hajri',false),
  (3,'Yearling Fillies','Harba Umm Aludham','QA','F','2025-04-13','Grey','Harbi Al Adwan','Da Magic Moment','Mr. Nasser Mohammed M A Al Hajri',false),
  (3,'Yearling Fillies','Fulla Umm Aludham','QA','F','2025-03-04','Grey','Figaro','Majdd','Al Ghashamiya Stud',false),
  (3,'Yearling Fillies','Aq Oula','QA','F','2025-04-25','Bay','Exagon Os','Waad Al Yacoub','Al Yacoub Stud',false),
  (3,'Yearling Fillies','Rafeea Al Shaqab','QA','F','2025-03-09','Grey','Alexxanderr','Kahlah Al Shaqab','Al Sada Stud',false),
  (3,'Yearling Fillies','Lujain Al Hamama','SA','F','2025-04-01','Grey','Saqaar Alaz','Shaimaa Alfariss Aa','Sheikh Jassim Saoud A J Al-Thani',false),
  (3,'Yearling Fillies','Hiba Mudhar','QA','F','2025-03-27','Grey','Hama Mudhar Mp','Layali Al Nasser','Sheikh Hamad Ali A Th Al Thani',false),
  (3,'Yearling Fillies','Asrar Mudhar','QA','F','2025-02-07','Grey','Rfi Farid','Ayoush Al Shaqab','Sheikh Hamad Ali A Th Al Thani',false),
  (3,'Yearling Fillies','Cady Mudhar','QA','F','2025-02-03','Bay','Exagon Os','Emira K','Sheikh Hamad Ali A Th Al-Thani',false),
  (3,'Yearling Fillies','Mashael Mudhar','QA','F','2025-01-22','Bay','D Shakhat','Shaikha Mudhar','Sheikh Hamad Ali A Th Al Thani',false),
  (3,'Yearling Fillies','Mayyas Mudhar','QA','F','2025-04-04','Chestnut','D Shakhat','Mt Bambina','Mr. Mansoor Ghanim A A  Al-Khayareen',false),
  (3,'Yearling Fillies','Sh Rabwah','ZA','F','2025-04-10','Grey','Aj Taj','Pse Razeelah','Muath Mohammed Abdulkarim Aba Numay',false),
  (3,'Yearling Fillies','Es Hoor','SA','F','2025-01-23','Bay','Mutabahi Al Hawajer','Shmokh Al Haitham','Hamad Mahdi M Alyami',false),
  (3,'Yearling Fillies','Shamekha Al Wajba','QA','F','2025-01-25','Grey','Tm Itaipu','J Shamasi','Al Wajba Stud',false),
  (3,'Yearling Fillies','Tswahen Almishraaf','QA','F','2025-01-02','Chestnut','Gazwan Al Sraiya','Bella Sedona','Al Mishraaf Stud',false),
  (3,'Yearling Fillies','Waad Alasl','SA','F','2025-08-25','Chestnut','Melih Al Zobair','Trussrsha','Mohammed Abdulhaq Abdulwahab Alkhars - Alasl Stud',false),
  (3,'Yearling Fillies','Kh Aya','SA','F','2025-02-10','Bay','Raoud Albidayer','Bw Amjad','Sons Of Mubark Bin Hindi Al Khaldi Company',false),
  (3,'Yearling Fillies','Salwat Al Shaqab','QA','F','2025-04-20','Grey','Harbi Al Adwan','Marieta Al Shaqab','Sons Of Mubark Bin Hindi Al Khaldi Company',false),
  (3,'Yearling Fillies','Mo Seba','AE','F','2025-11-14','Grey','Edwan Al Zobair','M.O Muntassira','Ali Mohammed Qamber Hajeeh',false),
  (3,'Yearling Fillies','Hk-Bashayir','QA','F','2025-01-05','Bay','Figaro','Maha Al Sraiya','Mr. Hamad Jumah A S Al-Kaabi',false),
  (3,'Yearling Fillies','A.K.A. Teha','QA','F','2025-02-18','Bay','Dominic M','Saten','Mr. Khalid Ali A Al-Obaidli',false),
  (3,'Yearling Fillies','Jumna Ns','BH','F','2025-03-01','Chestnut','Royal Asad','Am Nura','Husain Habib Hasan - Al Nassim Stud',false),
  (3,'Yearling Fillies','Mathayel Al Athba','QA','F','2025-02-10','Bay','Ghaith Al Zobair','Lyali Al Athba','Al Athba Stud',false),
  (3,'Yearling Fillies','Eishq Erab Alsahra','SA','F','2025-04-06','Bay','Eks Farajj','Maashogat Erab Al Sahhra','Saad Saleh Ibraheem  Bobshait',false),
  (3,'Yearling Fillies','Tamara Alshathliah','SA','F','2025-04-01','Bay','Mutabahi Al Hawajer','Cw Eleganza','Abdulaziz Abdulrahman Alothman',false),
  (6,'Yearling Colts','Sirajj Al Jazeel','QA','M','2025-01-11','Chestnut','D Shakhat','Royal Titania As','Al Jazeel Stud',false),
  (6,'Yearling Colts','Rayq Al Shaqab','QA','M','2025-03-20','Grey','Wf Gawin','Princess Marwan Rc','Mr. Nasser Salman N E Al-Mesallam',false),
  (6,'Yearling Colts','Lahab Al Nasser','QA','M','2025-02-02','Grey','D Seraj','Leena Al Nasser','Sheikh Khalid Nasser A A Al-Thani',false),
  (6,'Yearling Colts','Haddaj Al Sraiya','QA','M','2025-03-15','Grey','Harbi Al Adwan','Alkaydah Al Sraiya','Al Sraiya Stud',false),
  (6,'Yearling Colts','Harib Al Wajba','QA','M','2025-04-01','Grey','Harbi Al Adwan','Mb Doha','Al Atheel Stud',false),
  (6,'Yearling Colts','Nashwan Al Ammar','QA','M','2025-03-27','Grey','Halul Al Khor','Al Mubarkia Al Ammar','Al Ammar Stud',false),
  (6,'Yearling Colts','Shaheen Al Mohannad','QA','M','2025-11-11','Grey','Rajeh Al Adwan','Zumurruda Al Nasser','Abdullah Saad Hilal Al Mohannadi',false),
  (6,'Yearling Colts','Winchester Al Jood','QA','M','2025-02-02','Chestnut','D Wannas','Shurouq Al Nasser','Al Sada  Stud',false),
  (6,'Yearling Colts','Farr''A E''Thanya','QA','M','2025-05-04','Bay','Aj Radman','Farfalla Hhc','Al Hamama Stud',false),
  (6,'Yearling Colts','Ghaith Al Nasser','QA','M','2025-03-21','Grey','Tm Itaipu','Jolien Aljassimya','Sheikh Jassim Saoud A J Al-Thani',false),
  (6,'Yearling Colts','H Ghaith','QA','M','2025-05-01','Bay','Ghaith Al Zobair','Faidh Al Jfoul','Al Henzab Stud',false),
  (6,'Yearling Colts','H-Ornes','QA','M','2025-01-14','Bay','Mutabahi Al Hawajer','Mystica Soraya','Al Henzab Stud',false),
  (6,'Yearling Colts','Tael Al Jood','QA','M','2025-01-02','Grey','Talaal Serondella','Elkymia Al Jood','Al Dawasir Stud',false),
  (6,'Yearling Colts','Arkan Al Dawasir','BH','M','2025-02-20','Chestnut','Sq Wasim','Aj Nomah','Al Dawasir Stud',false),
  (6,'Yearling Colts','Lusail Mudhar','QA','M','2025-02-03','Bay','Exagon Os','Mb Querida','Sheikh Hamad Ali A Th Al-Thani',false),
  (6,'Yearling Colts','Bandar Mudhar','QA','M','2025-02-12','Grey','Exagon Os','Doha Mudhar Hvp','Sheikh Hamad Ali A Th Al Thani',false),
  (6,'Yearling Colts','Dukhan Mudhar','QA','M','2025-01-17','Grey','Medan Al Shaqab','Soufiya Al Shaqab','Sheikh Hamad Ali A Th Al-Thani',false),
  (6,'Yearling Colts','Najd Sh','QA','M','2025-01-18','Bay','Sa Faez Simbad','Sacarina O','Mr. Nasser Misfer H A Al-Hajri',false),
  (6,'Yearling Colts','Sharar Al Jazeel','QA','M','2025-03-15','Bay','D Shakhat','Emv Jyvanna El Madan','Ma Stud',false),
  (6,'Yearling Colts','Katheer Al Ramad','QA','M','2025-02-04','Bay','Wf Gawin','Autumn Wind Mtc','Alnasseria Farm',false),
  (6,'Yearling Colts','Nader Al Wajba','QA','M','2025-05-12','Grey','Baz Aljassimya','Nourah Al Khalediah','Al Wajba Stud',false),
  (6,'Yearling Colts','Sahm Alboraq','QA','M','2025-03-16','Bay','Sultan Al Zobara','Retaj Al Shaqab','Al Boraq Stud',false),
  (6,'Yearling Colts','Raad Alboraq','QA','M','2025-03-20','Grey','Sultan Al Zobara','Sama Alboraq','Al Boraq Stud',false),
  (6,'Yearling Colts','Kh Asad','SA','M','2025-02-20','Grey','El Tino','Sultana Al Jabriya','Sons Of Mubark Bin Hindi Al Khaldi Company',false),
  (6,'Yearling Colts','Razi Al Bahya','AE','M','2025-02-19','Grey','Aj Kafu','Aj Rafiqa','Sons Of Mubark Bin Hindi Al Khaldi Company',false),
  (6,'Yearling Colts','Najm Al Reeh','QA','M','2025-04-01','Bay','D Shajei','Caressa Svb','Al Dhabi Stud',false),
  (6,'Yearling Colts','Wafi Al Jood','QA','M','2025-11-04','Bay','D Wannas','Aj Bahja','Hassan Khalid S G Al-Ghanim',false),
  (6,'Yearling Colts','Wahaj Al Yusufiya','QA','M','2025-03-15','Grey','Ash''Al Al E''Zz','Mouhsina Al Shaqab','Al Yusufiya Arabians',false),
  (6,'Yearling Colts','El Cairo Ea','ES','M','2025-01-16','Grey','Shanghai Ea','Ebony E.A.','Mr. Mostafa Abdulrahman Rajab - Al Hayat Stud',false),
  (4,'Fillies 2 Years Old','Yara Al Nasser','BE','F','2024-02-26','Grey','E.S. Harir','Ashadiya','Sh. Nawaf Bin Nasser Al Thani - Al Nasser Stud',false),
  (4,'Fillies 2 Years Old','Ikram Al Nasser','QA','F','2024-04-04','Chestnut','Lr Solo Mio','Tahseen Al Zobair','Al Nasser Stud - Sheikh Nawaf Bin Nasser Al Thani',false),
  (4,'Fillies 2 Years Old','Aryam Al Sraiya','QA','F','2024-05-25','Grey','Excalibur Ea','Reem Al Sraiya','Al Sraiya Stud',false),
  (4,'Fillies 2 Years Old','Alia Al Khor K','BR','F','2024-04-15','Grey','Gt Shardh','Aaliyah K','Al Khor Stud',false),
  (4,'Fillies 2 Years Old','D Shagrah','QA','F','2024-01-01','Chestnut','D Fannan','D Ghamsharah','Al Khor Stud',false),
  (4,'Fillies 2 Years Old','Shihanah Kl','QA','F','2024-04-27','Grey','D Seraj','Dalma Kl','Kaheel Stud',false),
  (4,'Fillies 2 Years Old','Mz Afaal','AE','F','2024-01-31','Bay','Al Aryam Hasheem','Qr Andrea','Mr. Mesfer Mohammed Mesfer Al Hajri',false),
  (4,'Fillies 2 Years Old','Rds Remas','BE','F','2024-06-09','Grey','Ghaly Al Hawajer','Muranas Azeezah','Al Yacoub Stud',false),
  (4,'Fillies 2 Years Old','Tsaheel Al Shaqab','QA','F','2024-03-21','Grey','Excalibur Ea','Sarrah Al Jassimya','Sheikh Jassim Saoud A J Al-Thani',false),
  (4,'Fillies 2 Years Old','Antonina Cme','US','F','2024-02-14','Bay','Aria Rakeem','Sweet La Vita','Muath Mohammed Abdulkarim Aba Numay',false),
  (4,'Fillies 2 Years Old','D Wana','SA','F','2024-01-24','Chestnut','Exxalt','D Heba','Muath Mohammed Abdulkarim Aba Numay',false),
  (4,'Fillies 2 Years Old','Marseille','KW','F','2024-03-25','Bay','D Nather','Sophia','Mr. Mohammad Faleh Shafi Alajmi',false),
  (4,'Fillies 2 Years Old','Sumu Al Mushlah','QA','F','2024-02-10','Bay','Raad Lembarak','Wc Mariellaa','Mr. Abdulaziz Nasser M N Al-Khalifa',false),
  (4,'Fillies 2 Years Old','Kh Malath','SA','F','2024-02-01','Grey','Royal Asad','Wj Malak','Sons Of Mubark Bin Hindi Al Khaldi Company',false),
  (4,'Fillies 2 Years Old','Beisan Al Bahya','AE','F','2024-02-18','Grey','Aj Marzan','Aj Baynunah','Sons Of Mubark Bin Hindi Al Khaldi Company',false),
  (4,'Fillies 2 Years Old','Radifa Al Shaqab','QA','F','2024-10-30','Bay','Wf Gawin','Irinah','Sons Of Mubark Bin Hindi Al Khaldi Company',false),
  (4,'Fillies 2 Years Old','Mt Bateel','SA','F','2024-02-05','Bay','D Shakhat','Badawia Al Muawd','Khalid Abdulaziz Almousa',false),
  (4,'Fillies 2 Years Old','Makbola Al Shaqab','QA','F','2024-12-30','Grey','Berlin Mp','Nachmiya Al Shaqab','Al-Salimya Stud',false),
  (4,'Fillies 2 Years Old','Ey Manara','QA','F','2024-04-07','Grey','Excalibur Ea','Maaly','Mr. Khalifa Ali Kh Kh Al-Suwaidi',false),
  (4,'Fillies 2 Years Old','Napa Alnarh','SA','F','2024-06-21','Grey','Ferdan','Al Aryam Jenana','Mohamed Jaber Ayesh Ali Al Humaid',false),
  (7,'Colts 2 Years Old','Dstoor Al Sraiya','QA','M','2024-06-22','Grey','Excalibur Ea','Anoud Al Sraiya','Al Sraiya Stud',false),
  (7,'Colts 2 Years Old','Zenith Al Shahania','QA','M','2024-01-31','Bay','Lr Solo Mio','Anwar Al Shahania','Al Obayyah Stud',false),
  (7,'Colts 2 Years Old','Ob Aseel','QA','M','2024-04-10','Bay','Ghaith Al Zobair','Khatoon Al Shaqab','Al Obayyah Stud',false),
  (7,'Colts 2 Years Old','Dandon Kl','QA','M','2024-05-02','Grey','Lr Solo Mio','Motatra Al Enaya','Kaheel Stud',false),
  (7,'Colts 2 Years Old','Shakhat Al Shahania','QA','M','2024-03-31','Bay','Excalibur Ea','Saherha Al Shahania','Fahad Juma Al-Muhannadi',false),
  (7,'Colts 2 Years Old','Barq Umm Aludham','QA','M','2024-04-20','Grey','Ghaith Al Zobair','Aldana Umm Aludham','Essa Juma R D Al-Muhannadi',false),
  (7,'Colts 2 Years Old','Shaqran Aljassimya','QA','M','2024-04-07','Chestnut','Lehon','Jazanh Aljassimya','Mr. Mohammed Saad Al-Naimi',false),
  (7,'Colts 2 Years Old','Yazeed Mudhar','QA','M','2024-01-16','Grey','Rfi Farid','Doha Mudhar Hvp','Sheikh Hamad Ali A Th Al Thani',false),
  (7,'Colts 2 Years Old','Zsq Azzam','QA','M','2024-11-16','Grey','Miqdam Gulfa','Ma Deva','Mohammed Ghanim M K Al Hajri',false),
  (7,'Colts 2 Years Old','Hamza Al Jaham','QA','M','2024-04-01','Grey','Excalibur Ea','Bidayat Ibn Salamah','Al Jaham Stud',false),
  (7,'Colts 2 Years Old','Mh Lazaz','QA','M','2024-02-25','Grey','Shaman Al Zobara','Kholood Al Shaqab','Mh Stud',false),
  (7,'Colts 2 Years Old','Bahir Aa','QA','M','2024-03-10','Grey','S.M.A. Magic One','Nouf Aa','Mr. Ahmed Abdulla A A Al-Mohannadi',false),
  (7,'Colts 2 Years Old','Aser Althamryia','SA','M','2024-04-04','Grey','Aj Faik','Meral Bd','Mr. Essa Ali E I Al-Baloshi',false),
  (7,'Colts 2 Years Old','Arslan','KW','M','2024-05-23','Grey','Eks Farajj','Royal Eliza','Alaseelah Stud',false),
  (7,'Colts 2 Years Old','Sayer Al Bahya','QA','M','2024-11-11','Grey','Shanghai Ea','Aj Salwanah','Al Mashrab Stud',false),
  (7,'Colts 2 Years Old','Rakan Aljumail','QA','M','2024-03-07','Bay','Sa Faez Simbad','Assayla Al Shaqab','Al Boraq Stud',false),
  (7,'Colts 2 Years Old','Tawiq Dirgham','SA','M','2024-01-01','Chestnut','S M A Magic One','Taima Athbah','Mohammed Abdulhaq Abdulwahab Alkhars/Alasl Stud',false),
  (7,'Colts 2 Years Old','Shhab Al Zobair','DE','M','2024-10-06','Bay','Eks Farajj','Nawader Al Zobair','Abdullah Meishal Almeishal',false),
  (7,'Colts 2 Years Old','Fahad Al Zobair','QA','M','2024-02-05','Bay','Mazyoun Al Bidayer','Toflah Al Zobair','Aylan Stud',false),
  (7,'Colts 2 Years Old','Ar Ghaith','SA','M','2024-05-28','Bay','Ghaith Al Zobair','Mahbuba Al Muawd','Waleed Khalid Ali Almajed',false),
  (7,'Colts 2 Years Old','Al Wasm Ib','SA','M','2024-10-25','Grey','Karem Al Bahya','Rasmah','Fahad Abdullah Fahad Dakhel Alhaqbani Aldosari',false),
  (7,'Colts 2 Years Old','Bayan Al Yasser','EG','M','2024-04-25','Bay','Amir Al Yasser','Badreya  Al Yasser','Al Yasser Stud',false),
  (5,'Fillies 3 Years Old','D Hasbaa','QA','F','2023-01-20','Grey','Aj Ajban','D Jawharah','Al Khor Stud',false),
  (5,'Fillies 3 Years Old','Fay Aljassimya','QA','F','2023-06-11','Chestnut','Picasso Di Mar (It)','Fareeda Al Mar','Al Hamama Stud',false),
  (5,'Fillies 3 Years Old','Hessa Al Salem','QA','F','2023-03-10','Chestnut','Taiar Al Shaqab','Rihab Al Shaqab','Al Salem Stud',false),
  (5,'Fillies 3 Years Old','Rose Al Shahania','QA','F','2023-02-27','Bay','Rhan Al Shahania','Saherha Al Shahania','Al Jaham Stud',false),
  (5,'Fillies 3 Years Old','Haifa Al Tinhat','SA','F','2023-03-25','Grey','Mutabahi Al Hawajer','Noorah Al Tinhat','Al Ghashamiya Stud',false),
  (5,'Fillies 3 Years Old','Asfoorat Al Dana','QA','F','2023-11-04','Grey','Ghalab Al Shaqab','Asfoorat Al Safinat','Al Dana Stud',false),
  (5,'Fillies 3 Years Old','Emtenan Al Shahania','QA','F','2023-03-19','Bay','Rhan Al Shahania','Abha Qalams','Mr. Ibrahim Issa M H Alfadala',false),
  (5,'Fillies 3 Years Old','Jamrat Al Abdyah','SA','F','2023-04-24','Chestnut','Royal Asad','Sali Alenaya','Rayan Abdulrahman B Alsayqal-Alsayaqul Stud',false),
  (5,'Fillies 3 Years Old','Gezlan Al Saad','QA','F','2023-10-05','Bay','Gazwan Al Sraiya','Shoug Umm Aludham','Al Saad Stud',false),
  (5,'Fillies 3 Years Old','T A Ndawi','SA','F','2023-03-01','Chestnut','Aj Faik','Wadhhah Altaflan','Sons Of Mubark Bin Hindi Al Khaldi Company',false),
  (5,'Fillies 3 Years Old','Sawsan Al Shaqab','QA','F','2023-03-15','Grey','Eks Farajj','Ofw Emmalee','Sons Of Mubark Bin Hindi Al Khaldi Company',false),
  (5,'Fillies 3 Years Old','Qamrah Alnahiy','QA','F','2023-03-07','Bay','Wadee Al Shaqab','Kadi Al Shaqab','Jaralla Mohammed S A Al-Marri',false),
  (8,'Colts 3 Years Old','Azzam Umm Aludham','QA','M','2023-01-10','Bay','Badiea Al Nasser','Ahood Umm Aludham','Mr. Nasser Mohammed M A Al Hajri',false),
  (8,'Colts 3 Years Old','Elr Farouk Aa','BE','M','2023-06-21','Bay','Ghaly Al Hawajer','Fayrooz Aa','Al Yacoub Stud',false),
  (8,'Colts 3 Years Old','Damascus Pcf','US','M','2023-03-10','Bay','Dominic M','Aliyah Vision Pcf','Mohammed Saad K A Al-Naimi',false),
  (8,'Colts 3 Years Old','Santorini O','SE','M','2023-05-01','Grey','Wf Gawin','Gazals Serina','Al Dawasir Stud',false),
  (8,'Colts 3 Years Old','Sa Al Muthaqaf','QA','M','2023-08-23','Grey','Fahad Al Rayyan','Jawaher Al Naif','Salman Jassem Al Darwish',false),
  (8,'Colts 3 Years Old','Ghayyath Al Shaqab','QA','M','2023-04-24','Chestnut','Eks Farajj','Aijana','Sons Of Mubark Bin Hindi Al Khaldi Company',false),
  (8,'Colts 3 Years Old','Kh Habs','SA','M','2023-04-07','Bay','Royal Asad','Dhma Alaainah','Sons Of Mubark Bin Hindi Al Khaldi Company',false),
  (8,'Colts 3 Years Old','Meshal The Line','SA','M','2023-05-10','Bay','Ghaith Al Zobair','D Gezaila','Abdullah Meishal Almeishal',false),
  (8,'Colts 3 Years Old','Ghazi Al Sraiya','QA','M','2023-04-19','Chestnut','Gazwan Al Sraiya','Benedetta Inz','Al Mushlah Stud',false),
  (9,'Mares 4-6 Years Old','D Nashabeyyah','AE','F','2021-03-27','Grey','Excalibur Ea','D Muntaha','Al Jazeel Stud',false),
  (9,'Mares 4-6 Years Old','Taima Al Nasser','QA','F','2022-01-07','Grey','Excalibur Ea','Loulou Al Nasser','Al Nasser Stud - Sheikh Nawaf Bin Nasser Al Thani',false),
  (9,'Mares 4-6 Years Old','Jelsy Ma','DE','F','2022-04-11','Grey','Aj Nawash','Joleen Ma','Al Khor Stud',false),
  (9,'Mares 4-6 Years Old','Bahiya S B M','QA','F','2020-03-03','Bay','Fa El Rasheem','Muranas Je Taime','Nasser Mohammed M A Al Hajri',false),
  (9,'Mares 4-6 Years Old','D Wedad','AE','F','2022-02-21','Chestnut','Fa El Rasheem','D Wasayef','Mr. Nasser Mohammed M A Al Hajri',false),
  (9,'Mares 4-6 Years Old','Sabha Al Khor','QA','F','2021-10-12','Bay','Halul Al Khor','Rayyanat Al Khor','Al Dawasir Stud',false),
  (9,'Mares 4-6 Years Old','Farida Mudhar','QA','F','2022-04-02','Bay','Farid Al Hawajer','A. L. R. Aseela','Sheikh Hamad Ali A Th Al-Thani',false),
  (9,'Mares 4-6 Years Old','Shaikha Mudhar','QA','F','2022-01-10','Bay','Marajj','Nahawand Al Zobair','Sheikh Hamad Ali A Th Al Thani',false),
  (9,'Mares 4-6 Years Old','Bashayer Al Bawadi','QA','F','2020-01-21','Grey','Al Milan','Just This Once','Al Bawadi Stud',false),
  (9,'Mares 4-6 Years Old','Mayaan Al Laheef','QA','F','2021-03-06','Chestnut','Fa Starlight','Maharaani','Al Laheef Stud',false),
  (9,'Mares 4-6 Years Old','Meznah Almuawd','QA','F','2022-02-14','Grey','Fuerte','Mira Des Alpes','Albayariq Stud',false),
  (9,'Mares 4-6 Years Old','Lulu Alriffa','SA','F','2021-06-01','Chestnut','Aaser Athbah','Darjah Athbah','Rayan Abdulrahman B Alsayqal',false),
  (9,'Mares 4-6 Years Old','Mozn Albadr','AE','F','2021-01-27','Grey','S.M.A. Magic One','Gaja Luna','Ahmad Saleh Moshref',false),
  (9,'Mares 4-6 Years Old','Ferdous Al Nawader','BH','F','2022-01-20','Grey','Mushtabah Al Zobair','D Nameerah','Al Nawader Arabians (Bh)',false),
  (9,'Mares 4-6 Years Old','Bint Marzan','QA','F','2022-01-02','Grey','Aj Marzan','Aj Dina','Ahmad Abdulla A A Al-Kuwari',false),
  (12,'Stallions 4-6 Years Old','Omeir Al Sraiya','QA','M','2022-05-29','Bay','Amir Al Reeh','Shalfa Al Sraiya','Al Sraiya Stud',false),
  (12,'Stallions 4-6 Years Old','Jowel Mm','FR','M','2022-04-27','Bay','Jewel Rc','Haifa Al Adeyat','Al Obayyah Stud',false),
  (12,'Stallions 4-6 Years Old','Aj Tayam','AE','M','2021-10-28','Bay','Antaris Os','Aj Tarim','Mr. Nasser Mohammed M A Al Hajri',false),
  (12,'Stallions 4-6 Years Old','Bahi Al Jaham','QA','M','2020-11-10','Bay','Badiea Al Nasser','Brea Ea','Al Jaham Stud',false),
  (12,'Stallions 4-6 Years Old','Faris Al Nasiat','AE','M','2021-12-19','Grey','Emerald J','Aj Farha','Al Dana Stud',false),
  (12,'Stallions 4-6 Years Old','D Serdah','SA','M','2021-01-13','Chestnut','D Seraj','D Nawal','Essam Abu Bakur Ahmad Almalayo',false),
  (12,'Stallions 4-6 Years Old','Kahil Al Khuwair','QA','M','2022-12-01','Grey','Ghazi Al Nasser','Goot Al Shaqab','Al Khuwair Stud',false),
  (10,'Mares 7-10 Years Old','Alkaydah Al Sraiya','QA','F','2019-06-24','Grey','Naseem Al Rashediah','Makhida','Al Sraiya Stud',false),
  (10,'Mares 7-10 Years Old','Najla Umm Aludham','QA','F','2017-01-06','Grey','Wadee Al Shaqab','Da Magic Moment','Mr. Nasser Mohammed Mesfer Al Hajri',false),
  (10,'Mares 7-10 Years Old','D Fala','AE','F','2016-02-25','Grey','Emerald J','Fer Fiera Blanca','Al Salem Stud',false),
  (10,'Mares 7-10 Years Old','Zahra Al Yasrah','QA','F','2016-03-04','Grey','Wadee Al Shaqab','Bellatrix','Al Yasrah Stud',false),
  (10,'Mares 7-10 Years Old','Kholood Al Shaqab','QA','F','2017-12-22','Grey','Wh Justice','Rhr Vallacontessa','Mh Stud',false),
  (10,'Mares 7-10 Years Old','Ag Basma','SA','F','2017-07-27','Grey','Nahar Al Rashediah','F.E.S Chilly','Muath Mohammed Abdulkarim Aba Numay',false),
  (10,'Mares 7-10 Years Old','Anbara Al Shaqab','QA','F','2018-12-10','Grey','Shagran Al Nasser','Shalha Al Shaqab','Altuwaim Stud',false),
  (10,'Mares 7-10 Years Old','D Manawy','SA','F','2017-10-24','Bay','Fa El Rasheem','D Muna','Hamad Mahdi M Alyami',false),
  (10,'Mares 7-10 Years Old','Kiara Aljassimyya','US','F','2017-01-05','Grey','Equator','Karinena Dakar','Raed Saad Nasser Aldaghri',false),
  (10,'Mares 7-10 Years Old','Najla Athbah','BH','F','2019-05-27','Grey','Shanghai Ea','Treasure Nabila Jq','Mr Ali Abdali Fakharawi - Al Nassim Stud',false),
  (10,'Mares 7-10 Years Old','D Aasaleyyah','AE','F','2018-02-25','Chestnut','Fa El Rasheem','Elle Flamenca','Mostafa Abdulrahman Rajab',false),
  (13,'Stallions 7-10 Years Old','Badi Athbah','BE','M','2016-02-08','Bay','Eks Alihandro','Fedora Rg','Al Jazeel Stud',false),
  (13,'Stallions 7-10 Years Old','Kanz Lnj','SA','M','2018-04-04','Bay','Kanz Al Bidayer','Fadya Lnj','Hisham Abdullah Wakeel Alshaikh',false),
  (11,'Mares 11+ Years Old','Farona','DE','F','2011-03-31','Grey','Al Milan','Farida Bint Khidar','Mr. Nasser Mohammed M A Al Hajri',false),
  (11,'Mares 11+ Years Old','Abha Al Hamad','KW','F','2015-10-10','Grey','Aj Dhaen Al Shaaba','H Elana H','Mr. Khalid Meqbil F F Alqahtani',false),
  (11,'Mares 11+ Years Old','D Shatha','QA','F','2015-02-20','Grey','Rfi Farid','D Sahabah','Al Salem Stud',false),
  (11,'Mares 11+ Years Old','Fs Venezuela','SA','F','2013-02-15','Chestnut','Vervaldee','Fs Madeline','Muath Mohammed Abdulkarim Aba Numay',false),
  (11,'Mares 11+ Years Old','Jumana Del Palazzotto','KW','F','2014-01-26','Grey','Wh Justice','Zb Lamante','Raed Saad Nasser Aldaghri',false),
  (11,'Mares 11+ Years Old','Bint Sultan','QA','F','2015-02-03','Grey','Sultan Al Shaqab','As Michel','Al Adeed Stud',false),
  (14,'Stallions 11+ Years Old','Lammah Al Naif','QA','M','2013-01-27','Grey','Fadi Al Shaqab','Batoul Al Naif','Al Aswadiyah Stud',false),
  (14,'Stallions 11+ Years Old','Baher Al Shaqab','QA','M','2014-06-09','Bay','Kahil Al Shaqab','Vanessa Al Shaqab','Alnasseria Farm',false),
  (14,'Stallions 11+ Years Old','Zain Al Thumama','QA','M','2015-03-01','Bay','Wadee Al Shaqab','Elle Kaliyah','Al Boraq Stud',false),
  (14,'Stallions 11+ Years Old','Just Of Glory V','PL','M','2012-04-28','Grey','Wh Justice','Bess-Gloria','Nasser Khaled Nasser Aludail',false),
  (14,'Stallions 11+ Years Old','Falah Al Shaqab','IT','M','2013-05-17','Chestnut','Fadi Al Shaqab','Joseph Just Emotion','Al Adeed Stud',false),
  (1,'Filly Foals','Ghala Al Nasser','QA','F','2026-02-14','Bay','Ghaly Al Hawajer','Arwa Al Nasser','Al Nasser Stud - Sheikh Nawaf Bin Nasser Al Thani',false),
  (1,'Filly Foals','Bayan Al Nasser','QA','F','2026-02-20','Grey','Baz Aljassimya','Bshaier Al Nasser','Al Nasser Stud - Sheikh Nawaf Bin Nasser Al Thani',false),
  (1,'Filly Foals','Diyala Al Nasser','QA','F','2026-03-17','Grey','Tm Itaipu','Hattan Al Nasser','Al Nasser Stud - Sheikh Nawaf Bin Nasser Al Thani',false),
  (1,'Filly Foals','Lina Mudhar','QA','F','2026-03-15','Grey','Shiraz De Lafon (Fr)','A.L.R. Aseela','Sheikh Hamad Ali A Th Al-Thani',false),
  (1,'Filly Foals','Katara Mudhar','QA','F','2026-01-25','Bay','Ghaly Al Hawajer','Rodeena Al Zobair','Sheikh Hamad Ali A Th Al-Thani',false),
  (1,'Filly Foals','Lamia Mudhar','QA','F','2026-01-18','Grey','Shiraz De Lafon (Fr)','Sabha Mudhar','Sheikh Hamad Ali A Th Al-Thani',false),
  (1,'Filly Foals','Jasmine Mudhar','QA','F','2026-01-15','Grey','Amaar','Shaikha Mudhar','Sheikh Hamad Ali A Th Al-Thani',false),
  (1,'Filly Foals','Sakhiyah Al Ammar (Qa)','QA','F','2026-02-10','Bay','Badiea Al Nasser','Al Ammaria Al Ammar','Alammar Stud',false),
  (1,'Filly Foals','Almaha Umm Aludham','QA','F','2026-02-05','Bay','Aj Tayam','Mzoon Al Diriyah','Mesfer Mohammed Al-Hajri - Umm Aludham Stud (Qa)',false),
  (1,'Filly Foals','Mayar Al Ammar (Qa)','QA','F','2026-04-22','Chestnut','D Tumooh','Asrar Al Ammar','Al Ammar Stud',false),
  (1,'Filly Foals','Dakhtanus','QA','F','2026-01-07','Grey','Coperfield Ora','Kadi Al Shaqab','Mr. Jaralla Mohammed S A Al-Marri',false),
  (1,'Filly Foals','Mh Masah','QA','F','2026-01-05','Grey','Berlin Mp','Aysha Al Zobara','Mh Stud',false),
  (1,'Filly Foals','Jaleela Al Jaham','QA','F','2026-02-24','Grey','Rajeh Al Adwan','Marwa Al Kheesa','Al Jaham Stud',false),
  (1,'Filly Foals','Nooran Mudhar','QA','F','2026-02-06','Bay','Vitorio To','Farida Mudhar','Sheikh Hamad Ali A Th Al-Thani',false),
  (1,'Filly Foals','Naflah Al Ammar','QA','F','2026-02-20','Bay','Halul Al Khor','Tajweed Al Shaqab','Khalifa Abdulaziz K A Al Dosari',false),
  (1,'Filly Foals','Ajayeb Sh','QA','F','2026-03-01','Grey','Berlin Mp','Shareqat Al E''Zz','Mr. Nasser Misfer H A Al-Hajri',false),
  (1,'Filly Foals','Wilaya Al Shakra','QA','F','2026-03-12','Bay','Azzam Al Sraiya','El Masoufah','Al Shakra Stud',false),
  (1,'Filly Foals','Noora Hleetan (Qa)','QA','F','2026-03-15','Bay','Ghaly Al Hawajer','Rawdah Al Watan','Hleetan Stud',false),
  (1,'Filly Foals','Milhat Najd','QA','F','2026-01-30','Bay','Lehon','Bella Romantica Ga','Najd  Stud',false),
  (2,'Colt Foals','Sayaf Al Nasser','QA','M','2026-01-17','Grey','Tm Itaipu','Bdour Al Nasser','Al Hamama Stud',false),
  (2,'Colt Foals','Bashir Mudhar','QA','M','2026-04-25','Grey','Medan Al Shaqab','Shalwa Al Shaqab','Sheikh Hamad Ali A Th Al-Thani',false),
  (2,'Colt Foals','Ghaly Mudhar','QA','M','2026-03-10','Bay','Ghaly Al Hawajer','Farida Mudhar','Sheikh Hamad Ali A Th Al-Thani',false),
  (2,'Colt Foals','Gazal Mudhar','QA','M','2026-01-24','Bay','Rfi Unique','Shaikha Mudhar','Sheikh Hamad Ali A Th Al-Thani',false),
  (2,'Colt Foals','Ob Saham','QA','M','2026-04-03','Bay','Jowel Mm','Khatoon Al Shaqab','Al Obayyah Stud',false),
  (2,'Colt Foals','Ayyal Umm Aludham','QA','M','2026-01-02','Bay','Aj Tayam','Najla Umm Aludham','Mr Nasser Mohammed Misfer Al Hajiri',false),
  (2,'Colt Foals','Laith Umm Aludham','QA','M','2026-04-02','Bay','Lehon (It)','Al Jazi Umm Aludham','Mr Nasser Mohammed Misfer Al Hajiri',false),
  (2,'Colt Foals','Fahad Al Hamdan','QA','M','2026-02-17','Chestnut','Halul Al Khor','Rk Neom','Al Hamdan Stud',false),
  (2,'Colt Foals','Aq Sahm','QA','M','2026-02-06','Bay','Aj Nabhan','Aahd Al Yacoub','Al Yacoub Stud',false);
insert into public.app_meta (key, value) values ('updated_at', now()::text) on conflict (key) do update set value = excluded.value;
